# Generated by Django 4.2.13 on 2024-10-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_successstory_batch_late_batch_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='late_batch',
            field=models.BooleanField(default=False),
        ),
    ]
