# Generated by Django 4.2.13 on 2024-08-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chapter_image_course_image_lesson_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='title',
            new_name='chapter_name',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='lesson_name',
        ),
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
