# Generated by Django 4.2.13 on 2024-09-14 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_successstories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuccessStories',
            new_name='SuccessStory',
        ),
    ]
