# Generated by Django 4.2.13 on 2024-10-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_batch_late_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchlesson',
            name='visible_in_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='visible_in_days',
            field=models.IntegerField(default=0),
        ),
    ]
