# Generated by Django 4.2.13 on 2024-09-05 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_level_question_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='talentHunt',
        ),
        migrations.RemoveField(
            model_name='talenthunt',
            name='subject',
        ),
        migrations.CreateModel(
            name='TalentHuntSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.subject')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='talenthuntsubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.talenthuntsubject'),
        ),
    ]
