# Generated by Django 4.2.13 on 2024-09-05 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_level_talenthunt_remove_talenthunt_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talenthuntsubject',
            name='talentHunt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.talenthunt'),
        ),
    ]
