# Generated by Django 4.2.13 on 2024-09-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_talenthuntsubject_talenthunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
