# Generated by Django 4.2.13 on 2024-09-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='batch',
        ),
        migrations.AddField(
            model_name='subscription',
            name='batch',
            field=models.ManyToManyField(to='dashboard.batch'),
        ),
    ]
