# Generated by Django 4.2.13 on 2024-09-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_folder_created_folder_is_deleted_folder_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='dashboard.chapter'),
        ),
    ]
