# Generated by Django 4.2.13 on 2024-08-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_customuser_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='created',
            new_name='start_date',
        ),
    ]
