# Generated by Django 4.2.13 on 2024-09-29 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_lesson_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.PositiveIntegerField(choices=[(1, 'Text'), (2, 'Image'), (3, 'Multiple Choice')], default=1),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='BathLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.batch')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lesson')),
            ],
        ),
    ]
