# Generated by Django 4.2.13 on 2024-09-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathlesson',
            name='visible_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_lessons',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
