# Generated by Django 4.2.13 on 2024-09-02 10:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_exam_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
