# Generated by Django 4.2.13 on 2024-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_bathlesson_visible_days_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
