# Generated by Django 4.2.13 on 2024-09-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_course_duration_alter_course_number_of_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='visible_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
