"""
Django settings for Sahakari_Race_Plus project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import  os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0a%7(0#r%kze8wv8j!7g089%@%f3d#a=fs=4l9nb!h(zuh5qkg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
CRISPY_TEMPLATE_PACK = "bootstrap4"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    'crispy_forms',
    'django.contrib.humanize',
    'crispy_bootstrap4',
    # 'multiselectfield'
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Sahakari_Race_Plus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates" ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Sahakari_Race_Plus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join("static"), os.path.join(BASE_DIR, "static/")]
STATIC_ROOT = "assets/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_RESTRICT_BY_DATE = False
CKEDITOR_IMAGE_BACKEND = "ckeditor_uploader.backends.PillowBackend"
MEDIA_URL = "/media/"
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": [
            # {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-']},
            {"name": "clipboard", "items": ["Undo", "Redo"]},
            {"name": "editing", "items": ["Find", "Replace"]},
            # {'name': 'forms',
            #  'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
            #    'HiddenField']},
            # '/',
            {
                "name": "basicstyles",
                "items": [
                    "Bold",
                    "Italic",
                    "Underline",
                    "Strike",
                    "Subscript",
                    "Superscript",
                    "-",
                    "RemoveFormat",
                ],
            },
            {
                "name": "paragraph",
                "items": [
                    "NumberedList",
                    "BulletedList",
                    "-",
                    "Outdent",
                    "Indent",
                    "-",
                    "Blockquote",
                    "-",
                    "JustifyLeft",
                    "JustifyCenter",
                    "JustifyRight",
                    "JustifyBlock",
                ],
            },
            {"name": "links", "items": ["Link", "Unlink"]},
            {
                "name": "insert",
                "items": [
                    "Image",
                    "Flash",
                    "Table",
                    "HorizontalRule",
                    "SpecialChar",
                    "Preview",
                ],
            },
            "/",
            {"name": "styles", "items": ["Styles", "Format", "Font", "FontSize"]},
            # {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            # {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            # {'name': 'about', 'items': ['About']},
            {"name": "youtube", "items": ["Youtube"]},
            {"name": "math", "items": ["Mathjax"]},
        ],
        #   [
        #  {'name': 'youcustomtools', 'items': [
        # 'Save',
        # 'Source',
        # 'Image',
        # 'Embed',
        # 'Mathjax',
        # 'Preview',
        # ]},
        # ],
        "font_names": "Poppins/Poppins",
        "fontSize_sizes": "16/16px;",
        "contentsCss": [
            "https://fonts.googleapis.com/css2?family=Poppins:wght@400&display=swap",
            "/static/css/ckeditor_contents.css",  # Assuming you have a CSS file in static files
        ],
        "bodyClass": "poppins-text",
        "mathJaxLib": "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML",
        "tabSpaces": 4,
        "extraPlugins": ",".join(
            [
                "mathjax",
                "embed",
                # "imageuploader",
                "youtube",
            ]
        ),
        # "removeButtons": 'Underline,Subscript,Superscript',
        # "format_tags": 'p;h1;h2;h3;pre',
        # "removeDialogTabs": 'image:advanced;link:advanced',
        "youtube_disabled_fields": "txtEmbed,chkAutoplay",
        "youtube_width": "640",
        "youtube_height": "480",
        "youtube_responsive": True,
        "youtube_older": False,
        "youtube_related": True,
        "youtube_autoplay": False,
        "youtube_controls": True,
        "youtube_privacy": False,
        # 'embed_provider': '//ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}&api_key=' + IFRAMELY_API_KEY,
        # "extraAllowedContent": "iframe[*]",
        "removePlugins": ["iframe"],
        "allowedContent": True,
        "height": 150,
    },
    "option_ckeditor": {
        "toolbar": [
            # {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-']},
            # {'name': 'clipboard', 'items': [ 'Undo', 'Redo']},
            # {'name': 'editing', 'items': ['Find', 'Replace']},
            # {'name': 'forms',
            #  'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
            #    'HiddenField']},
            # '/',
            # {'name': 'basicstyles',
            #  'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            #     {'name': 'paragraph',
            #      'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-',
            #                'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']},
            #     {'name': 'links', 'items': ['Link', 'Unlink']},
            #    {'name': 'insert',
            #      'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'SpecialChar','Preview']},
            # '/',
            # {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            # {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            # {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            # {'name': 'about', 'items': ['About']},
            {"name": "math", "items": ["Mathjax"]}
        ],
        #   [
        #  {'name': 'youcustomtools', 'items': [
        # 'Save',
        # 'Source',
        # 'Image',
        # 'Embed',
        # 'Mathjax',
        # 'Preview',
        # ]},
        # ],
        "font_names": "Poppins/Poppins",
        "fontSize_sizes": "16/16px;",
        "contentsCss": [
            "https://fonts.googleapis.com/css2?family=Poppins:wght@400&display=swap",
            "/static/css/ckeditor_contents.css",
        ],
        "bodyClass": "poppins-text",
        "mathJaxLib": "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML",
        "tabSpaces": 4,
        "extraPlugins": ",".join(
            [
                "mathjax",
                "embed",
            ]
        ),
        "height": 70,
        # 'width': 500,
    },
}